import { useState, useEffect } from 'react';
import { Shield, Search, Filter, Trash2, RefreshCw, ChevronLeft, ChevronRight, Clock } from 'lucide-react';
import { useAuth } from '@/context/AuthContext';
import { Button } from '@/components/ui/button';
import toast from 'react-hot-toast';

const ACTION_COLORS = {
  ROLE_CHANGED:        'badge-purple',
  UPDATED_INVENTORY:   'badge-info',
  DELETED_PRODUCT:     'badge-destructive',
  CREATED_PRODUCT:     'badge-success',
  UPDATED_PRODUCT:     'badge-warning',
  DEFAULT:             'badge-secondary',
};

export default function AuditLog() {
  const { token } = useAuth();
  const [logs, setLogs] = useState([]);
  const [loading, setLoading] = useState(true);
  const [total, setTotal] = useState(0);
  const [page, setPage] = useState(1);
  const limit = 25;

  // Filters
  const [filters, setFilters] = useState({ action: '', entity: '', from: '', to: '' });
  const [applied, setApplied] = useState({});

  const fetchLogs = async (currentPage = 1, currentFilters = {}) => {
    setLoading(true);
    try {
      const params = new URLSearchParams({ page: currentPage, limit });
      if (currentFilters.action) params.set('action', currentFilters.action);
      if (currentFilters.entity) params.set('entity', currentFilters.entity);
      if (currentFilters.from) params.set('from', currentFilters.from);
      if (currentFilters.to) params.set('to', currentFilters.to);

      const res = await fetch(`${import.meta.env.VITE_API_URL}/api/support/audit-logs?${params}`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      const json = await res.json();
      if (json.success) {
        setLogs(json.data);
        setTotal(json.total);
      } else {
        toast.error('Failed to load audit logs');
      }
    } catch {
      toast.error('Network error');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => { fetchLogs(page, applied); }, [page, applied]);

  const handleApplyFilters = () => { setPage(1); setApplied({ ...filters }); };
  const handleClearFilters = () => { setFilters({ action: '', entity: '', from: '', to: '' }); setPage(1); setApplied({}); };

  const handleDelete = async (id) => {
    if (!window.confirm('Delete this audit log entry? This action cannot be undone.')) return;
    try {
      const res = await fetch(`${import.meta.env.VITE_API_URL}/api/support/audit-logs/${id}`, {
        method: 'DELETE',
        headers: { Authorization: `Bearer ${token}` }
      });
      const json = await res.json();
      if (json.success) {
        toast.success('Audit log entry deleted');
        setLogs(prev => prev.filter(l => l.id !== id));
        setTotal(prev => prev - 1);
      } else {
        toast.error(json.message || 'Failed to delete');
      }
    } catch {
      toast.error('Network error');
    }
  };

  const totalPages = Math.ceil(total / limit);

  return (
    <div className="space-y-6 animate-in fade-in duration-500">
      <div className="page-header mb-0">
        <div className="page-header-icon bg-primary/10 text-primary">
          <Shield size={22} />
        </div>
        <div className="flex-1">
          <h1 className="page-title">Audit Logs</h1>
          <p className="page-subtitle">Read-only record of all system actions. Logs are written automatically and cannot be created manually.</p>
        </div>
        <Button variant="outline" size="sm" onClick={() => fetchLogs(page, applied)} className="flex items-center gap-2">
          <RefreshCw size={14} /> Refresh
        </Button>
      </div>

      {/* Industry Standard Notice */}
      <div className="bg-blue-50 border border-blue-200 dark:bg-blue-900/20 dark:border-blue-800 rounded-xl p-4 flex items-start gap-3">
        <Clock size={16} className="text-blue-600 shrink-0 mt-0.5" />
        <p className="text-sm text-blue-700 dark:text-blue-400">
          <strong>Industry Standard:</strong> Audit logs are automatically generated by the system for every privileged action. They cannot be manually created or edited — only read and, by SUPER_ADMIN/OWNER, deleted for compliance archival purposes.
        </p>
      </div>

      {/* Filters */}
      <div className="form-card">
        <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
          <div>
            <label className="form-label text-xs">Action</label>
            <input
              type="text"
              placeholder="e.g. ROLE_CHANGED"
              value={filters.action}
              onChange={e => setFilters(f => ({ ...f, action: e.target.value }))}
              className="w-full rounded-xl border border-input bg-background px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary"
            />
          </div>
          <div>
            <label className="form-label text-xs">Entity</label>
            <input
              type="text"
              placeholder="e.g. User, Product"
              value={filters.entity}
              onChange={e => setFilters(f => ({ ...f, entity: e.target.value }))}
              className="w-full rounded-xl border border-input bg-background px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary"
            />
          </div>
          <div>
            <label className="form-label text-xs">From Date</label>
            <input type="date" value={filters.from} onChange={e => setFilters(f => ({ ...f, from: e.target.value }))}
              className="w-full rounded-xl border border-input bg-background px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary" />
          </div>
          <div>
            <label className="form-label text-xs">To Date</label>
            <input type="date" value={filters.to} onChange={e => setFilters(f => ({ ...f, to: e.target.value }))}
              className="w-full rounded-xl border border-input bg-background px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary" />
          </div>
        </div>
        <div className="flex justify-end gap-2 mt-4">
          <Button variant="outline" size="sm" onClick={handleClearFilters}>Clear</Button>
          <Button size="sm" onClick={handleApplyFilters}><Search size={14} className="mr-1.5" /> Apply Filters</Button>
        </div>
      </div>

      {/* Table */}
      <div className="data-table-wrapper">
        <div className="data-table-header">
          <p className="text-sm font-semibold text-foreground">{total.toLocaleString()} Total Records</p>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead className="border-b border-border bg-primary/5">
              <tr className="text-xs font-bold text-muted-foreground uppercase tracking-wider">
                <th className="data-table-cell text-left">Timestamp</th>
                <th className="data-table-cell text-left">User</th>
                <th className="data-table-cell text-left">Action</th>
                <th className="data-table-cell text-left">Entity</th>
                <th className="data-table-cell text-left">Entity ID</th>
                <th className="data-table-cell text-right">Delete</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              {loading ? (
                [...Array(8)].map((_, i) => (
                  <tr key={i}>
                    {[...Array(6)].map((_, j) => (
                      <td key={j} className="data-table-cell"><div className="h-4 bg-muted rounded animate-pulse" /></td>
                    ))}
                  </tr>
                ))
              ) : logs.length === 0 ? (
                <tr>
                  <td colSpan={6} className="py-16 text-center text-muted-foreground">
                    <Shield size={36} className="mx-auto mb-2 opacity-30" />
                    <p className="font-medium">No audit logs found</p>
                    <p className="text-xs mt-1">Try adjusting your filters.</p>
                  </td>
                </tr>
              ) : logs.map(log => (
                <tr key={log.id} className="data-table-row">
                  <td className="data-table-cell text-muted-foreground text-xs whitespace-nowrap">
                    {new Date(log.createdAt).toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' })}
                  </td>
                  <td className="data-table-cell">
                    <div>
                      <p className="font-semibold text-foreground text-xs">{log.user?.firstName} {log.user?.lastName}</p>
                      <p className="text-xs text-muted-foreground">{log.user?.role?.replace(/_/g, ' ')}</p>
                    </div>
                  </td>
                  <td className="data-table-cell">
                    <span className={`badge ${ACTION_COLORS[log.action] || ACTION_COLORS.DEFAULT}`}>
                      {log.action.replace(/_/g, ' ')}
                    </span>
                  </td>
                  <td className="data-table-cell font-medium text-foreground">{log.entity}</td>
                  <td className="data-table-cell">
                    <code className="text-xs bg-muted px-1.5 py-0.5 rounded font-mono">{log.entityId?.substring(0, 8)}…</code>
                  </td>
                  <td className="data-table-cell text-right">
                    <button
                      onClick={() => handleDelete(log.id)}
                      className="p-1.5 rounded-lg text-muted-foreground hover:text-destructive hover:bg-destructive/10 transition-colors"
                      title="Delete log entry"
                    >
                      <Trash2 size={14} />
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>

        {/* Pagination */}
        {totalPages > 1 && (
          <div className="flex items-center justify-between px-6 py-4 border-t border-border">
            <p className="text-xs text-muted-foreground">
              Page {page} of {totalPages} ({total} total entries)
            </p>
            <div className="flex items-center gap-2">
              <Button variant="outline" size="sm" onClick={() => setPage(p => Math.max(1, p - 1))} disabled={page === 1}>
                <ChevronLeft size={14} />
              </Button>
              <Button variant="outline" size="sm" onClick={() => setPage(p => Math.min(totalPages, p + 1))} disabled={page === totalPages}>
                <ChevronRight size={14} />
              </Button>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
